---

- name: Get current user ID
  ansible.builtin.command:
    cmd: id -u
  register: debian_update_user_id
  changed_when: false

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
 #   dpkg_options:
 #     - "{{ debian_update_dpkg_options }}"

- name: Upgrade all packages
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    update_cache: false
    upgrade: dist

- name: Check if a reboot is necessary because the file exists '{{ debian_update_reboot_check_file }}'
  ansible.builtin.stat:
    path: "{{ debian_update_reboot_check_file }}"
    get_checksum: false
  register: debian_update_reboot_required_file

- name: Check if a reboot is necessary because of different kernel versions
  when: ansible_facts["virtualization_type"] != "lxc"
  block:
    - name: Get running kernel version from uname
      ansible.builtin.command: uname -r
      register: debian_update_running_kernel
      changed_when: false

    - name: Get installed kernel version from /boot
      ansible.builtin.shell: |
        set -o pipefail
        ls -1 /boot/vmlinuz-* | sed 's/.*vmlinuz-//' | sort -V | tail -1
      args:
        executable: /bin/bash
      register: debian_update_installed_kernel
      changed_when: false

    - name: Compare versions
      ansible.builtin.set_fact:
        debian_update_reboot_required_kernel: "{{ debian_update_running_kernel.stdout != debian_update_installed_kernel.stdout }}"

- name: Notify handler if reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required"
  notify: Reboot the server
  changed_when: true
  when: (debian_update_reboot_required_file.stat.exists or (debian_update_reboot_required_kernel | default(false)))

- name: Flush handlers to reboot immediately if needed
  ansible.builtin.meta: flush_handlers

- name: Remove old packages from the cache
  ansible.builtin.apt:
    autoclean: true
    clean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
    purge: true
