---

# Determine if a path exists and is a directory.  Note that we need to test
# both that p.stat.isdir actually exists, and also that it's set to true.
- name: Check if path exists and is a directory "{{ docker_compose_update_project_src }}"
  ansible.builtin.stat:
    path: "{{ docker_compose_update_project_src }}"
  register: p
- name: Print a debug message
  ansible.builtin.debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir
- name: Fail if path does not exist or is not a directory
  ansible.builtin.fail:
    msg: "Path does not exist or is not a directory"
  when: p.stat.isdir is not defined or not p.stat.isdir
- name: Pull images for "{{ docker_compose_update_project_src }}"
  community.docker.docker_compose_v2_pull:
    project_src: "{{ docker_compose_update_project_src }}"

#- name: Tear down existing services
#  community.docker.docker_compose_v2:
#    project_src: "{{ docker_compose_update_project_src }}"
#    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_update_project_src }}"
    state: present
  register: output

- name: Prune images
  community.docker.docker_prune:
    images: true

- name: Show results
  ansible.builtin.debug:
    var: output
